@baseUrl=http://localhost:8080/api

### 상품 가입 (계좌 자동 생성됨)
POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "memberId": 1,
  "productId": 1,
  "accountNumber": "123-4567-8910"
}

### 내 가입 내역 조회
GET {{baseUrl}}/subscriptions/member/1

### 관리자 검색 (like 검색)
GET {{baseUrl}}/subscriptions/admin/search?keyword=user

### 중도 해지
POST {{baseUrl}}/subscriptions/1/cancel
